
server.port=8081

spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=duser87@yandex.ru
spring.mail.password=Stm32_ex_131313.
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true