
services:
  postgres:
    image: postgres:16
    env_file: local.env
    ports:
      - "5432:5432"

  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file: local.env
    command:
      - java -jar app.jar
volumes:
  postgres_data: