
services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homework05.2
    volumes:
      - ./input.txt:/app/input.txt
      - ./output.txt:/app/output.txt
    command: ["java", "-jar", "app.jar"]